package labconnect.controller;

import com.labconnect.models.LabReport;
import com.labconnect.services.DashboardService;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Optional;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;

@WebMvcTest(DashboardController.class)
public class DashboardControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean // Replaces deprecated @MockBean
    private DashboardService dashboardService;

    @Test
    @WithMockUser(username = "analyst", roles = {"Technician"})
    public void testGetReportById_Success() throws Exception {
        // Arrange
        LabReport report = new LabReport();
        // Since reportId is generated by DB, we manually set it for the mock
        // (Note: You may need to add a setter if @Data doesn't cover it or use reflection)
        Mockito.when(dashboardService.getReportById(1L)).thenReturn(Optional.of(report));

        // Act & Assert
        mockMvc.perform(get("/api/dashboard/reports/1")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());
    }

    @Test
    public void testAccessDenied_WithoutUser() throws Exception {
        // Act & Assert
        mockMvc.perform(get("/api/dashboard/reports"))
                .andExpect(status().isUnauthorized());
    }
}